name: CI

on:
  push:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .php_cs
      - docs/**
      - README.md
  pull_request:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .php_cs
      - docs/**
      - README.md

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl json mbstring
      - name: Install composer dependencies
        run: |
          composer --version && composer install --no-progress
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./vendor/*" -exec php -l {} \;
      - name: Run unit tests
        run: |
          vendor/bin/phpunit -c tests/phpunit.xml.dist
  sonar-cloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: curl json mbstring
      - name: Install composer dependencies
        run: |
          composer --version
          composer install --no-progress
      - name: Run unit tests
        run: |
          vendor/bin/phpunit -c tests/phpunit.xml.dist
      - name: Send code coverage report to coveralls.io
        run: vendor/bin/php-coveralls -v
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Run psalm
        run: |
          vendor/bin/psalm --no-progress
      - name: Run infection
        run: |
          vendor/bin/infection --no-progress --min-msi=94 --threads=4
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
